#!/usr/bin/env python3
"""Generate the grid module's real solid harmonic tables (Schlegel
convention) and emit grid/include/qcx/grid/internal/solid_harmonics.hpp.

The AO-value-at-point evaluator evaluates S_lm(r) for every angular
momentum the basis parser accepts (l = 0..6, the SPDFGHI/I-shell cap).
Its convention is the Schlegel normalization, int S_lm^2 dOmega =
4 pi / (2l + 1) - the same solid harmonics the integrals module's engine
uses per-primitive (unit self-overlap for every l).  The engine's
generated tables (tools/gen_md_tables.py, kSolidHarmonicG) carry the
Racah rows (orthonormal under the angular monomial metric W: G W G^T =
I), so the Schlegel row is the Racah row scaled by
sqrt(4 pi / (2l + 1)).

The module DAG forbids grid -> integrals includes, so the table is
generated INTO the grid module from the same machinery the integrals
generator uses (md.solid_harmonic_table, exact rational coefficients at
30 digits) - consistency between the two modules is by construction
(identical generator input) and is certified twice here: the Racah rows
pass G W G^T = I (checked inside solid_harmonic_table) and the scaled
rows pass the Schlegel certificate G W G^T = diag(4 pi / (2l + 1)) at
the working precision.

Usage:  python tools/grid/gen_solid_harmonics.py            # regenerate
        python tools/grid/gen_solid_harmonics.py --check    # verify the header
Output: grid/include/qcx/grid/internal/solid_harmonics.hpp
"""

from __future__ import annotations

import os
import sys
import tempfile
from pathlib import Path

# The generators share one machinery module: put the tools directory on
# the path (the script's parent's parent) and import it read-only.
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
import gen_md_tables as md  # noqa: E402

MAX_L = 6  # matches kMaxShellAngularMomentum (basis_set.cpp): I shells.
OUT_PATH = "grid/include/qcx/grid/internal/solid_harmonics.hpp"


def schlegel_rows(l):
    """The Schlegel-normalized rows (m = -l..+l) as mpf lists, scaled from
    the Racah rows and certified: G W G^T = diag(4 pi / (2l + 1))."""
    racah = md.solid_harmonic_table(l)
    # l = 0 is the identity row [1] (the Racah fold starts at l = 1, see
    # solid_harmonic_table): S00 = 1 needs no scaling and already has the
    # Schlegel norm 4 pi = 4 pi / (2l + 1).  l >= 1 rows are orthonormal
    # under W (G W G^T = I), so the Schlegel row is Racah * sqrt(4 pi / (2l + 1)).
    scale = md.mpf(1) if l == 0 else md.sqrt(4 * md.pi / (2 * l + 1))
    rows = [[md.mpf(v) * scale for v in row] for row in racah]

    carts = md.cartesian_components(l)
    W = [[md.angular_moment(i[0] + j[0], i[1] + j[1], i[2] + j[2]) for j in carts] for i in carts]
    target = 4 * md.pi / (2 * l + 1)
    for m1 in range(len(rows)):
        for m2 in range(len(rows)):
            value = sum(rows[m1][a] * W[a][b] * rows[m2][b]
                        for a in range(len(carts)) for b in range(len(carts)))
            want = target if m1 == m2 else md.mpf(0)
            if abs(value - want) > md.mpf(10) ** -28:
                raise SystemExit(f"Schlegel certificate l={l} m1={m1} m2={m2}: "
                                 f"<S|S> = {md.mp.nstr(value, 30)}, expected {md.mp.nstr(want, 30)}")
    return rows


def write_solid_harmonics_header(path):
    all_terms = []
    all_rows = []  # per l: 13-wide list of (offset, count) pairs, m index = m + l

    for l in range(MAX_L + 1):
        rows = schlegel_rows(l)
        per_l = [(0, 0)] * 13

        for m in range(-l, l + 1):
            offset = len(all_terms)
            count = 0
            for cart, coeff in enumerate(rows[m + l]):
                if coeff == 0:
                    continue
                ix, iy, iz = md.cartesian_components(l)[cart]
                all_terms.append((md.mp.nstr(coeff, 30), ix, iy, iz))
                count += 1
            per_l[m + l] = (offset, count)

        all_rows.append(per_l)

    with open(path, "w", newline="\n") as f:
        f.write("// Generated by tools/grid/gen_solid_harmonics.py - DO NOT EDIT.\n")
        f.write("// Real solid harmonics S_lm(x, y, z), Schlegel convention\n")
        f.write("// (int S_lm^2 dOmega = 4 pi / (2l + 1)), l = 0..6, m order -l..+l with\n")
        f.write("// m < 0 the sine component and m > 0 the cosine component.  Rows are the\n")
        f.write("// integrals engine's Racah rows (tools/gen_md_tables.py kSolidHarmonicG,\n")
        f.write("// G W G^T = I under the angular monomial metric W) scaled by\n")
        f.write("// sqrt(4 pi / (2l + 1)); the generator certifies the scaled rows against\n")
        f.write("// G W G^T = diag(4 pi / (2l + 1)) at 30 digits.  The grid module cannot\n")
        f.write("// include the integrals tables (module DAG), so the same generator\n")
        f.write("// machinery emits them here - consistency across modules is by\n")
        f.write("// construction.  The basis module renormalizes spherical contractions\n")
        f.write("// against exactly this convention (SameShellPrimitiveOverlap in\n")
        f.write("// basis_set.cpp), so these coefficients are exact as stored.\n")
        f.write("#pragma once\n\n")
        f.write("#include <array>\n#include <cstddef>\n#include <cstdint>\n\n")
        f.write("namespace qcx::grid::internal {\n\n")
        f.write("/// The highest angular momentum with generated rows (the basis parser's\n")
        f.write("/// I-shell cap).\n")
        f.write("inline constexpr int kMaxSolidHarmonicL = 6;\n\n")
        f.write("/// One monomial term c * x^ix y^iy z^iz of a solid-harmonic row.\n")
        f.write("struct SolidHarmonicTerm {\n")
        f.write("    double coefficient; ///< The monomial coefficient c.\n")
        f.write("    std::uint8_t ix;    ///< The x exponent.\n")
        f.write("    std::uint8_t iy;    ///< The y exponent.\n")
        f.write("    std::uint8_t iz;    ///< The z exponent.\n")
        f.write("};\n\n")
        f.write("/// Row (l, m): the slot is kSolidHarmonicRows[l * 13 + (m + l)], holding\n")
        f.write("/// the term range kSolidHarmonicTerms[offset .. offset + count).  The\n")
        f.write("/// table is flat (13 slots per l, 91 total); slots past 2l in each\n")
        f.write("/// block are explicit {0, 0} padding - MSVC 19.51 rejects constexpr\n")
        f.write("/// nested std::array with struct elements (C2078/C2131), so the rows\n")
        f.write("/// stay 1-D.\n")
        f.write("struct SolidHarmonicRow {\n")
        f.write("    std::uint32_t offset; ///< Start of the term range in kSolidHarmonicTerms.\n")
        f.write("    std::uint8_t count;  ///< Number of terms in the range (0 = unused slot).\n")
        f.write("};\n\n")
        f.write("inline constexpr std::size_t kSolidHarmonicRowSlotsPerL = 13;\n\n")
        f.write("inline constexpr auto kSolidHarmonicRows = std::to_array<SolidHarmonicRow>({\n")
        for l in range(MAX_L + 1):
            for m in range(-l, l + 1):
                offset, count = all_rows[l][m + l]
                f.write(f"    {{{offset}, {count}}},  // l={l}, m={m}\n")
            for m in range(l + 1, 2 * MAX_L - l + 1):
                f.write("    {0, 0},  // l=" + str(l) + ", m=" + str(m) + " (unused)\n")
        f.write("});\n\n")
        f.write("inline constexpr auto kSolidHarmonicTerms = std::to_array<SolidHarmonicTerm>({\n")
        for coeff, ix, iy, iz in all_terms:
            f.write(f"    {{{coeff}, {ix}, {iy}, {iz}}},\n")
        f.write("});\n\n")
        f.write("}  // namespace qcx::grid::internal\n")


def main():
    check_only = "--check" in sys.argv

    repo_root = Path(__file__).resolve().parent.parent.parent
    path = repo_root / OUT_PATH

    if check_only:
        fd, tmp = tempfile.mkstemp(suffix=".hpp", prefix="solid-harm-check-",
                                   dir=os.path.dirname(path))
        try:
            os.close(fd)
            write_solid_harmonics_header(tmp)
            md.format_header(tmp)
            with open(tmp, "rb") as fresh, open(path, "rb") as committed:
                if fresh.read() != committed.read():
                    print(f"DRIFT: {path} differs from a fresh generation")
                    return 1
        finally:
            os.remove(tmp)
        return 0

    os.makedirs(os.path.dirname(path), exist_ok=True)
    write_solid_harmonics_header(path)
    md.format_header(path)
    print(f"wrote {path}")


if __name__ == "__main__":
    sys.exit(main())
