// Generated by tools/gen_md_tables.py - DO NOT EDIT.
// The per-{L_bra, L_ket}-class function-pointer table; entries whose
// class lies outside the instantiation matrix (the 2e triangle UNION
// the RI rectangle at the configured QcxIntegralsLMax) are nullptr -
// no CI configuration ever links the full class matrix.
#pragma once
#include "md_engine.hpp"

namespace qcx::integrals::internal {

inline constexpr auto kMdClassTableF64 = std::to_array<std::array<MdClassFnF64, 13>>({
    {
// L_bra=0
#if (QcxIntegralsLMax >= 0)
        &ComputeEriClass<0, 0>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 1)
        &ComputeEriClass<0, 1>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 1)
        &ComputeEriClass<0, 2>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 2)
        &ComputeEriClass<0, 3>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 2)
        &ComputeEriClass<0, 4>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 3)
        &ComputeEriClass<0, 5>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 3)
        &ComputeEriClass<0, 6>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 4)
        &ComputeEriClass<0, 7>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 4)
        &ComputeEriClass<0, 8>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 5)
        &ComputeEriClass<0, 9>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 5)
        &ComputeEriClass<0, 10>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 6)
        &ComputeEriClass<0, 11>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 6)
        &ComputeEriClass<0, 12>,
#else
        nullptr,
#endif
    },
    {
// L_bra=1
#if (QcxIntegralsLMax >= 1)
        &ComputeEriClass<1, 0>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 1)
        &ComputeEriClass<1, 1>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 1)
        &ComputeEriClass<1, 2>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 2)
        &ComputeEriClass<1, 3>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 2)
        &ComputeEriClass<1, 4>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 3)
        &ComputeEriClass<1, 5>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 3)
        &ComputeEriClass<1, 6>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 4)
        &ComputeEriClass<1, 7>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 4)
        &ComputeEriClass<1, 8>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 5)
        &ComputeEriClass<1, 9>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 5)
        &ComputeEriClass<1, 10>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 6)
        &ComputeEriClass<1, 11>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 6)
        &ComputeEriClass<1, 12>,
#else
        nullptr,
#endif
    },
    {
// L_bra=2
#if (QcxIntegralsLMax >= 1)
        &ComputeEriClass<2, 0>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 1)
        &ComputeEriClass<2, 1>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 1)
        &ComputeEriClass<2, 2>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 2)
        &ComputeEriClass<2, 3>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 2)
        &ComputeEriClass<2, 4>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 3)
        &ComputeEriClass<2, 5>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 3)
        &ComputeEriClass<2, 6>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 4)
        &ComputeEriClass<2, 7>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 4)
        &ComputeEriClass<2, 8>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 5)
        &ComputeEriClass<2, 9>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 5)
        &ComputeEriClass<2, 10>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 6)
        &ComputeEriClass<2, 11>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 6)
        &ComputeEriClass<2, 12>,
#else
        nullptr,
#endif
    },
    {
// L_bra=3
#if (QcxIntegralsLMax >= 2)
        &ComputeEriClass<3, 0>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 2)
        &ComputeEriClass<3, 1>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 2)
        &ComputeEriClass<3, 2>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 2)
        &ComputeEriClass<3, 3>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 2)
        &ComputeEriClass<3, 4>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 3)
        &ComputeEriClass<3, 5>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 3)
        &ComputeEriClass<3, 6>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 4)
        &ComputeEriClass<3, 7>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 4)
        &ComputeEriClass<3, 8>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 5)
        &ComputeEriClass<3, 9>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 5)
        &ComputeEriClass<3, 10>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 6)
        &ComputeEriClass<3, 11>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 6)
        &ComputeEriClass<3, 12>,
#else
        nullptr,
#endif
    },
    {
// L_bra=4
#if (QcxIntegralsLMax >= 2)
        &ComputeEriClass<4, 0>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 2)
        &ComputeEriClass<4, 1>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 2)
        &ComputeEriClass<4, 2>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 3)
        &ComputeEriClass<4, 3>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 2)
        &ComputeEriClass<4, 4>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 3)
        &ComputeEriClass<4, 5>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 3)
        &ComputeEriClass<4, 6>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 4)
        &ComputeEriClass<4, 7>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 4)
        &ComputeEriClass<4, 8>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 5)
        &ComputeEriClass<4, 9>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 5)
        &ComputeEriClass<4, 10>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 6)
        &ComputeEriClass<4, 11>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 6)
        &ComputeEriClass<4, 12>,
#else
        nullptr,
#endif
    },
    {
// L_bra=5
#if (QcxIntegralsLMax >= 3)
        &ComputeEriClass<5, 0>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 3)
        &ComputeEriClass<5, 1>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 3)
        &ComputeEriClass<5, 2>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 3)
        &ComputeEriClass<5, 3>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 4)
        &ComputeEriClass<5, 4>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 3)
        &ComputeEriClass<5, 5>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 3)
        &ComputeEriClass<5, 6>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 4)
        &ComputeEriClass<5, 7>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 4)
        &ComputeEriClass<5, 8>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 5)
        &ComputeEriClass<5, 9>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 5)
        &ComputeEriClass<5, 10>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 6)
        &ComputeEriClass<5, 11>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 6)
        &ComputeEriClass<5, 12>,
#else
        nullptr,
#endif
    },
    {
// L_bra=6
#if (QcxIntegralsLMax >= 3)
        &ComputeEriClass<6, 0>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 3)
        &ComputeEriClass<6, 1>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 3)
        &ComputeEriClass<6, 2>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 3)
        &ComputeEriClass<6, 3>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 4)
        &ComputeEriClass<6, 4>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 5)
        &ComputeEriClass<6, 5>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 3)
        &ComputeEriClass<6, 6>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 4)
        &ComputeEriClass<6, 7>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 4)
        &ComputeEriClass<6, 8>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 5)
        &ComputeEriClass<6, 9>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 5)
        &ComputeEriClass<6, 10>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 6)
        &ComputeEriClass<6, 11>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 6)
        &ComputeEriClass<6, 12>,
#else
        nullptr,
#endif
    },
    {
// L_bra=7
#if (QcxIntegralsLMax >= 4)
        &ComputeEriClass<7, 0>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 4)
        &ComputeEriClass<7, 1>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 4)
        &ComputeEriClass<7, 2>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 4)
        &ComputeEriClass<7, 3>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 4)
        &ComputeEriClass<7, 4>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 5)
        &ComputeEriClass<7, 5>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 6)
        &ComputeEriClass<7, 6>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 4)
        &ComputeEriClass<7, 7>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 4)
        &ComputeEriClass<7, 8>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 5)
        &ComputeEriClass<7, 9>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 5)
        &ComputeEriClass<7, 10>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 6)
        &ComputeEriClass<7, 11>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 6)
        &ComputeEriClass<7, 12>,
#else
        nullptr,
#endif
    },
    {
// L_bra=8
#if (QcxIntegralsLMax >= 4)
        &ComputeEriClass<8, 0>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 4)
        &ComputeEriClass<8, 1>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 4)
        &ComputeEriClass<8, 2>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 4)
        &ComputeEriClass<8, 3>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 4)
        &ComputeEriClass<8, 4>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 5)
        &ComputeEriClass<8, 5>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 6)
        &ComputeEriClass<8, 6>,
#else
        nullptr,
#endif
        nullptr, // beyond the 2e triangle and the RI rectangle
#if (QcxIntegralsLMax >= 4)
        &ComputeEriClass<8, 8>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 5)
        &ComputeEriClass<8, 9>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 5)
        &ComputeEriClass<8, 10>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 6)
        &ComputeEriClass<8, 11>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 6)
        &ComputeEriClass<8, 12>,
#else
        nullptr,
#endif
    },
    {
// L_bra=9
#if (QcxIntegralsLMax >= 5)
        &ComputeEriClass<9, 0>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 5)
        &ComputeEriClass<9, 1>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 5)
        &ComputeEriClass<9, 2>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 5)
        &ComputeEriClass<9, 3>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 5)
        &ComputeEriClass<9, 4>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 5)
        &ComputeEriClass<9, 5>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 6)
        &ComputeEriClass<9, 6>,
#else
        nullptr,
#endif
        nullptr, // beyond the 2e triangle and the RI rectangle
        nullptr, // beyond the 2e triangle and the RI rectangle
#if (QcxIntegralsLMax >= 5)
        &ComputeEriClass<9, 9>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 5)
        &ComputeEriClass<9, 10>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 6)
        &ComputeEriClass<9, 11>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 6)
        &ComputeEriClass<9, 12>,
#else
        nullptr,
#endif
    },
    {
// L_bra=10
#if (QcxIntegralsLMax >= 5)
        &ComputeEriClass<10, 0>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 5)
        &ComputeEriClass<10, 1>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 5)
        &ComputeEriClass<10, 2>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 5)
        &ComputeEriClass<10, 3>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 5)
        &ComputeEriClass<10, 4>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 5)
        &ComputeEriClass<10, 5>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 6)
        &ComputeEriClass<10, 6>,
#else
        nullptr,
#endif
        nullptr, // beyond the 2e triangle and the RI rectangle
        nullptr, // beyond the 2e triangle and the RI rectangle
        nullptr, // beyond the 2e triangle and the RI rectangle
#if (QcxIntegralsLMax >= 5)
        &ComputeEriClass<10, 10>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 6)
        &ComputeEriClass<10, 11>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 6)
        &ComputeEriClass<10, 12>,
#else
        nullptr,
#endif
    },
    {
// L_bra=11
#if (QcxIntegralsLMax >= 6)
        &ComputeEriClass<11, 0>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 6)
        &ComputeEriClass<11, 1>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 6)
        &ComputeEriClass<11, 2>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 6)
        &ComputeEriClass<11, 3>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 6)
        &ComputeEriClass<11, 4>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 6)
        &ComputeEriClass<11, 5>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 6)
        &ComputeEriClass<11, 6>,
#else
        nullptr,
#endif
        nullptr, // beyond the 2e triangle and the RI rectangle
        nullptr, // beyond the 2e triangle and the RI rectangle
        nullptr, // beyond the 2e triangle and the RI rectangle
        nullptr, // beyond the 2e triangle and the RI rectangle
#if (QcxIntegralsLMax >= 6)
        &ComputeEriClass<11, 11>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 6)
        &ComputeEriClass<11, 12>,
#else
        nullptr,
#endif
    },
    {
// L_bra=12
#if (QcxIntegralsLMax >= 6)
        &ComputeEriClass<12, 0>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 6)
        &ComputeEriClass<12, 1>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 6)
        &ComputeEriClass<12, 2>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 6)
        &ComputeEriClass<12, 3>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 6)
        &ComputeEriClass<12, 4>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 6)
        &ComputeEriClass<12, 5>,
#else
        nullptr,
#endif
#if (QcxIntegralsLMax >= 6)
        &ComputeEriClass<12, 6>,
#else
        nullptr,
#endif
        nullptr, // beyond the 2e triangle and the RI rectangle
        nullptr, // beyond the 2e triangle and the RI rectangle
        nullptr, // beyond the 2e triangle and the RI rectangle
        nullptr, // beyond the 2e triangle and the RI rectangle
        nullptr, // beyond the 2e triangle and the RI rectangle
#if (QcxIntegralsLMax >= 6)
        &ComputeEriClass<12, 12>,
#else
        nullptr,
#endif
    },
});

inline constexpr auto kMdClassTableF32 = std::to_array<std::array<MdClassFnF32, 13>>({
    {
// L_bra=0
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 0)
        &ComputeEriClassF32<0, 0>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 1)
        &ComputeEriClassF32<0, 1>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 1)
        &ComputeEriClassF32<0, 2>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 2)
        &ComputeEriClassF32<0, 3>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 2)
        &ComputeEriClassF32<0, 4>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 3)
        &ComputeEriClassF32<0, 5>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 3)
        &ComputeEriClassF32<0, 6>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 4)
        &ComputeEriClassF32<0, 7>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 4)
        &ComputeEriClassF32<0, 8>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 5)
        &ComputeEriClassF32<0, 9>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 5)
        &ComputeEriClassF32<0, 10>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 6)
        &ComputeEriClassF32<0, 11>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 6)
        &ComputeEriClassF32<0, 12>,
#else
        nullptr,
#endif
    },
    {
// L_bra=1
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 1)
        &ComputeEriClassF32<1, 0>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 1)
        &ComputeEriClassF32<1, 1>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 1)
        &ComputeEriClassF32<1, 2>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 2)
        &ComputeEriClassF32<1, 3>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 2)
        &ComputeEriClassF32<1, 4>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 3)
        &ComputeEriClassF32<1, 5>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 3)
        &ComputeEriClassF32<1, 6>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 4)
        &ComputeEriClassF32<1, 7>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 4)
        &ComputeEriClassF32<1, 8>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 5)
        &ComputeEriClassF32<1, 9>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 5)
        &ComputeEriClassF32<1, 10>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 6)
        &ComputeEriClassF32<1, 11>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 6)
        &ComputeEriClassF32<1, 12>,
#else
        nullptr,
#endif
    },
    {
// L_bra=2
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 1)
        &ComputeEriClassF32<2, 0>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 1)
        &ComputeEriClassF32<2, 1>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 1)
        &ComputeEriClassF32<2, 2>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 2)
        &ComputeEriClassF32<2, 3>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 2)
        &ComputeEriClassF32<2, 4>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 3)
        &ComputeEriClassF32<2, 5>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 3)
        &ComputeEriClassF32<2, 6>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 4)
        &ComputeEriClassF32<2, 7>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 4)
        &ComputeEriClassF32<2, 8>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 5)
        &ComputeEriClassF32<2, 9>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 5)
        &ComputeEriClassF32<2, 10>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 6)
        &ComputeEriClassF32<2, 11>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 6)
        &ComputeEriClassF32<2, 12>,
#else
        nullptr,
#endif
    },
    {
// L_bra=3
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 2)
        &ComputeEriClassF32<3, 0>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 2)
        &ComputeEriClassF32<3, 1>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 2)
        &ComputeEriClassF32<3, 2>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 2)
        &ComputeEriClassF32<3, 3>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 2)
        &ComputeEriClassF32<3, 4>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 3)
        &ComputeEriClassF32<3, 5>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 3)
        &ComputeEriClassF32<3, 6>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 4)
        &ComputeEriClassF32<3, 7>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 4)
        &ComputeEriClassF32<3, 8>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 5)
        &ComputeEriClassF32<3, 9>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 5)
        &ComputeEriClassF32<3, 10>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 6)
        &ComputeEriClassF32<3, 11>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 6)
        &ComputeEriClassF32<3, 12>,
#else
        nullptr,
#endif
    },
    {
// L_bra=4
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 2)
        &ComputeEriClassF32<4, 0>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 2)
        &ComputeEriClassF32<4, 1>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 2)
        &ComputeEriClassF32<4, 2>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 3)
        &ComputeEriClassF32<4, 3>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 2)
        &ComputeEriClassF32<4, 4>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 3)
        &ComputeEriClassF32<4, 5>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 3)
        &ComputeEriClassF32<4, 6>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 4)
        &ComputeEriClassF32<4, 7>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 4)
        &ComputeEriClassF32<4, 8>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 5)
        &ComputeEriClassF32<4, 9>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 5)
        &ComputeEriClassF32<4, 10>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 6)
        &ComputeEriClassF32<4, 11>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 6)
        &ComputeEriClassF32<4, 12>,
#else
        nullptr,
#endif
    },
    {
// L_bra=5
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 3)
        &ComputeEriClassF32<5, 0>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 3)
        &ComputeEriClassF32<5, 1>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 3)
        &ComputeEriClassF32<5, 2>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 3)
        &ComputeEriClassF32<5, 3>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 4)
        &ComputeEriClassF32<5, 4>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 3)
        &ComputeEriClassF32<5, 5>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 3)
        &ComputeEriClassF32<5, 6>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 4)
        &ComputeEriClassF32<5, 7>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 4)
        &ComputeEriClassF32<5, 8>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 5)
        &ComputeEriClassF32<5, 9>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 5)
        &ComputeEriClassF32<5, 10>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 6)
        &ComputeEriClassF32<5, 11>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 6)
        &ComputeEriClassF32<5, 12>,
#else
        nullptr,
#endif
    },
    {
// L_bra=6
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 3)
        &ComputeEriClassF32<6, 0>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 3)
        &ComputeEriClassF32<6, 1>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 3)
        &ComputeEriClassF32<6, 2>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 3)
        &ComputeEriClassF32<6, 3>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 4)
        &ComputeEriClassF32<6, 4>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 5)
        &ComputeEriClassF32<6, 5>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 3)
        &ComputeEriClassF32<6, 6>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 4)
        &ComputeEriClassF32<6, 7>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 4)
        &ComputeEriClassF32<6, 8>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 5)
        &ComputeEriClassF32<6, 9>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 5)
        &ComputeEriClassF32<6, 10>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 6)
        &ComputeEriClassF32<6, 11>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 6)
        &ComputeEriClassF32<6, 12>,
#else
        nullptr,
#endif
    },
    {
// L_bra=7
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 4)
        &ComputeEriClassF32<7, 0>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 4)
        &ComputeEriClassF32<7, 1>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 4)
        &ComputeEriClassF32<7, 2>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 4)
        &ComputeEriClassF32<7, 3>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 4)
        &ComputeEriClassF32<7, 4>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 5)
        &ComputeEriClassF32<7, 5>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 6)
        &ComputeEriClassF32<7, 6>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 4)
        &ComputeEriClassF32<7, 7>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 4)
        &ComputeEriClassF32<7, 8>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 5)
        &ComputeEriClassF32<7, 9>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 5)
        &ComputeEriClassF32<7, 10>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 6)
        &ComputeEriClassF32<7, 11>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 6)
        &ComputeEriClassF32<7, 12>,
#else
        nullptr,
#endif
    },
    {
// L_bra=8
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 4)
        &ComputeEriClassF32<8, 0>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 4)
        &ComputeEriClassF32<8, 1>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 4)
        &ComputeEriClassF32<8, 2>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 4)
        &ComputeEriClassF32<8, 3>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 4)
        &ComputeEriClassF32<8, 4>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 5)
        &ComputeEriClassF32<8, 5>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 6)
        &ComputeEriClassF32<8, 6>,
#else
        nullptr,
#endif
        nullptr, // beyond the 2e triangle and the RI rectangle
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 4)
        &ComputeEriClassF32<8, 8>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 5)
        &ComputeEriClassF32<8, 9>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 5)
        &ComputeEriClassF32<8, 10>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 6)
        &ComputeEriClassF32<8, 11>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 6)
        &ComputeEriClassF32<8, 12>,
#else
        nullptr,
#endif
    },
    {
// L_bra=9
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 5)
        &ComputeEriClassF32<9, 0>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 5)
        &ComputeEriClassF32<9, 1>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 5)
        &ComputeEriClassF32<9, 2>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 5)
        &ComputeEriClassF32<9, 3>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 5)
        &ComputeEriClassF32<9, 4>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 5)
        &ComputeEriClassF32<9, 5>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 6)
        &ComputeEriClassF32<9, 6>,
#else
        nullptr,
#endif
        nullptr, // beyond the 2e triangle and the RI rectangle
        nullptr, // beyond the 2e triangle and the RI rectangle
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 5)
        &ComputeEriClassF32<9, 9>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 5)
        &ComputeEriClassF32<9, 10>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 6)
        &ComputeEriClassF32<9, 11>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 6)
        &ComputeEriClassF32<9, 12>,
#else
        nullptr,
#endif
    },
    {
// L_bra=10
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 5)
        &ComputeEriClassF32<10, 0>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 5)
        &ComputeEriClassF32<10, 1>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 5)
        &ComputeEriClassF32<10, 2>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 5)
        &ComputeEriClassF32<10, 3>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 5)
        &ComputeEriClassF32<10, 4>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 5)
        &ComputeEriClassF32<10, 5>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 6)
        &ComputeEriClassF32<10, 6>,
#else
        nullptr,
#endif
        nullptr, // beyond the 2e triangle and the RI rectangle
        nullptr, // beyond the 2e triangle and the RI rectangle
        nullptr, // beyond the 2e triangle and the RI rectangle
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 5)
        &ComputeEriClassF32<10, 10>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 6)
        &ComputeEriClassF32<10, 11>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 6)
        &ComputeEriClassF32<10, 12>,
#else
        nullptr,
#endif
    },
    {
// L_bra=11
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 6)
        &ComputeEriClassF32<11, 0>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 6)
        &ComputeEriClassF32<11, 1>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 6)
        &ComputeEriClassF32<11, 2>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 6)
        &ComputeEriClassF32<11, 3>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 6)
        &ComputeEriClassF32<11, 4>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 6)
        &ComputeEriClassF32<11, 5>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 6)
        &ComputeEriClassF32<11, 6>,
#else
        nullptr,
#endif
        nullptr, // beyond the 2e triangle and the RI rectangle
        nullptr, // beyond the 2e triangle and the RI rectangle
        nullptr, // beyond the 2e triangle and the RI rectangle
        nullptr, // beyond the 2e triangle and the RI rectangle
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 6)
        &ComputeEriClassF32<11, 11>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 6)
        &ComputeEriClassF32<11, 12>,
#else
        nullptr,
#endif
    },
    {
// L_bra=12
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 6)
        &ComputeEriClassF32<12, 0>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 6)
        &ComputeEriClassF32<12, 1>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 6)
        &ComputeEriClassF32<12, 2>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 6)
        &ComputeEriClassF32<12, 3>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 6)
        &ComputeEriClassF32<12, 4>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 6)
        &ComputeEriClassF32<12, 5>,
#else
        nullptr,
#endif
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 6)
        &ComputeEriClassF32<12, 6>,
#else
        nullptr,
#endif
        nullptr, // beyond the 2e triangle and the RI rectangle
        nullptr, // beyond the 2e triangle and the RI rectangle
        nullptr, // beyond the 2e triangle and the RI rectangle
        nullptr, // beyond the 2e triangle and the RI rectangle
        nullptr, // beyond the 2e triangle and the RI rectangle
#if defined(QcxIntegralsF32) && (QcxIntegralsF32 == 1) && (QcxIntegralsLMax >= 6)
        &ComputeEriClassF32<12, 12>,
#else
        nullptr,
#endif
    },
});

} // namespace qcx::integrals::internal
