// The 8.7 acceptance: the committed pyscf (libcint) reference CSVs for
// H2O/cc-pVDZ (storage/tests/data/h2o_ccpvdz_class_*.csv, generated by
// tools/gen_stage8_reference.py) are compared against the classes
// persisted through the decorator and served from disk. A row is
// `eri,i,j,k,l,f,value` with f the EriBlockIndex flat offset in the
// quartet's block - the layout contract is pinned against an independent
// engine (PySCF, [Pyscf2018]). The CSVs are
// generated locally (pyscf runs in WSL, not CI); the test skips when they
// are absent.
#include "fast_test_mode.hpp"
#include "h2o_ccpvdz.hpp"
#include "qcx/integrals/eri_batch.hpp"
#include "qcx/storage/cached_eri_batch_engine.hpp"
#include "temp_store.hpp"

#include <algorithm>
#include <cstddef>
#include <filesystem>
#include <fstream>
#include <gtest/gtest.h>
#include <map>
#include <sstream>
#include <string>
#include <tuple>
#include <utility>
#include <vector>

namespace {

using qcx::integrals::BuildShellPairs;
using qcx::integrals::ComputeEriBatch;
using qcx::integrals::EriBatch;
using qcx::integrals::ShellFunctionCount;
using qcx::integrals::ShellPairList;
using qcx::integrals::ShellQuartet;
using qcx::storage::CachedEriBatchEngine;
using qcx::testing::MakeH2oCcpvdz;
using qcx::testing::MakeH2oCcpvdzBasis;
using qcx::testing::TempStoreFile;

constexpr double kReferenceTolerance = 1e-10;

struct ReferenceRow {
    std::size_t i;
    std::size_t j;
    std::size_t k;
    std::size_t l;
    std::size_t flatOffset;
    double value;
};

std::vector<ReferenceRow> LoadReference(const std::filesystem::path& csvPath) {
    std::vector<ReferenceRow> rows;
    std::ifstream in(csvPath);

    if (!in)
    {
        return rows;
    }

    std::string line;
    bool header = true;

    while (std::getline(in, line))
    {
        if (line.empty())
        {
            continue;
        }

        if (header)
        {
            header = false;
            continue;
        }

        std::replace(line.begin(), line.end(), ',', ' ');
        std::istringstream parser(line);
        std::string tag;
        ReferenceRow row{};

        if (!(parser >> tag >> row.i >> row.j >> row.k >> row.l >> row.flatOffset >> row.value))
        {
            return {};
        }

        rows.push_back(row);
    }

    return rows;
}

// The class of a canonical quartet.
std::pair<int, int> ClassOf(const ShellPairList& pairList, const ShellQuartet& quartet) {
    return {pairList.shells[quartet.i].angularMomentum + pairList.shells[quartet.j].angularMomentum,
            pairList.shells[quartet.k].angularMomentum +
                pairList.shells[quartet.l].angularMomentum};
}

// The canonical quartets of one class (the 8-fold form plus the class
// canonical form L_bra <= L_ket, exactly as CanonicalizeQuartetOrder
// defines it).
std::vector<ShellQuartet> ClassQuartets(const ShellPairList& pairList, int lBra, int lKet) {
    std::vector<ShellQuartet> quartets;

    for (std::size_t i = 0; i < pairList.shells.size(); ++i)
    {
        for (std::size_t j = i; j < pairList.shells.size(); ++j)
        {
            for (std::size_t k = 0; k < pairList.shells.size(); ++k)
            {
                for (std::size_t l = k; l < pairList.shells.size(); ++l)
                {
                    ShellQuartet candidate{i, j, k, l};

                    if (qcx::integrals::PairIndexOf(candidate.i, candidate.j, pairList) <
                        qcx::integrals::PairIndexOf(candidate.k, candidate.l, pairList))
                    {
                        continue;
                    }

                    if (ClassOf(pairList, candidate) != std::make_pair(lBra, lKet))
                    {
                        continue;
                    }

                    quartets.push_back(candidate);
                }
            }
        }
    }

    return quartets;
}

// The block element count of one canonical quartet.
std::size_t BlockElementCount(const ShellPairList& pairList, const ShellQuartet& quartet) {
    return ShellFunctionCount(pairList.shells[quartet.i]) *
           ShellFunctionCount(pairList.shells[quartet.j]) *
           ShellFunctionCount(pairList.shells[quartet.k]) *
           ShellFunctionCount(pairList.shells[quartet.l]);
}

TEST(PyscfCrossCheckTest, PersistedSetMatchesPyscf) {
    if (qcx::testing::IsFastOnlyMode())
    {
        GTEST_SKIP() << "the cc-pvdz class sweep is a full integrals run";
    }

    const auto molecule = MakeH2oCcpvdz();
    ASSERT_TRUE(molecule.has_value()) << molecule.error().message;
    const auto basis = MakeH2oCcpvdzBasis();
    ASSERT_TRUE(basis.has_value()) << basis.error().message;

    auto pairList = BuildShellPairs(*molecule, *basis);
    ASSERT_TRUE(pairList.has_value()) << pairList.error().message;

    const std::filesystem::path dataDir(QcxStorageDataDir);
    const std::vector<std::pair<int, int>> classes = {{0, 0}, {0, 1}, {0, 2}, {1, 1}};

    for (const auto& klass : classes)
    {
        const std::string csvName = "h2o_ccpvdz_class_" + std::to_string(klass.first) + "_" +
                                    std::to_string(klass.second) + ".csv";
        const std::filesystem::path csvPath = dataDir / csvName;

        if (!std::filesystem::exists(csvPath))
        {
            GTEST_SKIP() << "missing reference " << csvPath.string()
                         << " (run tools/gen_stage8_reference.py in WSL)";
        }

        const std::vector<ReferenceRow> rows = LoadReference(csvPath);
        ASSERT_FALSE(rows.empty()) << csvPath.string();

        const std::vector<ShellQuartet> quartets =
            ClassQuartets(*pairList, klass.first, klass.second);
        ASSERT_FALSE(quartets.empty()) << csvName;

        // Persist the class through the decorator, then serve it from disk.
        CachedEriBatchEngine::UnderlyingEngine engine =
            [&](const std::vector<qcx::integrals::ShellQuartet>& request) {
                return qcx::integrals::ComputeEriBatch(*molecule, *basis, request);
            };

        const std::filesystem::path storePath = TempStoreFile::MakePath(csvName);
        auto cached =
            CachedEriBatchEngine::Create(storePath, *molecule, *basis, "cc-pvdz", "", engine, {});
        ASSERT_TRUE(cached.has_value()) << cached.error().message;

        const auto first = cached->ComputeEriBatch(quartets);
        ASSERT_TRUE(first.has_value()) << first.error().message;
        const auto served = cached->ComputeEriBatch(quartets);
        ASSERT_TRUE(served.has_value()) << served.error().message;
        ASSERT_EQ(served->computed.size(), quartets.size()) << csvName;

        // The packed-block offset of every served quartet (prefix sums in
        // the canonical order).
        std::vector<std::size_t> blockOffset(served->computed.size(), 0);

        for (std::size_t q = 1; q < served->computed.size(); ++q)
        {
            blockOffset[q] =
                blockOffset[q - 1] + BlockElementCount(*pairList, served->computed[q - 1]);
        }

        // The CSV covers exactly the class's packed block elements.
        std::size_t totalBlocks =
            blockOffset.back() + BlockElementCount(*pairList, served->computed.back());
        EXPECT_EQ(totalBlocks, rows.size()) << csvName;

        // Quartet -> position in the served order.
        std::map<std::tuple<std::size_t, std::size_t, std::size_t, std::size_t>, std::size_t>
            position;

        for (std::size_t q = 0; q < served->computed.size(); ++q)
        {
            const ShellQuartet& quartet = served->computed[q];
            position[{quartet.i, quartet.j, quartet.k, quartet.l}] = q;
        }

        std::size_t checked = 0;

        for (const ReferenceRow& row : rows)
        {
            const auto it = position.find({row.i, row.j, row.k, row.l});
            ASSERT_NE(it, position.end()) << csvName << ": quartet (" << row.i << "," << row.j
                                          << "|" << row.k << "," << row.l << ") not served";
            const double actual = served->values[blockOffset[it->second] + row.flatOffset];
            EXPECT_NEAR(actual, row.value, kReferenceTolerance)
                << csvName << " (" << row.i << "," << row.j << "|" << row.k << "," << row.l
                << ") f=" << row.flatOffset;
            ++checked;
        }

        EXPECT_EQ(checked, rows.size()) << csvName;
    }
}

} // namespace
