#pragma once

// The storage tests' temp-file helper: a unique path under
// std::filesystem::temp_directory_path() per call (per-process counter),
// with RAII removal. The Windows-lock rule: the file handle lives inside
// the store, so the store (or cached engine) must be destroyed BEFORE the
// TempStoreFile - declare the TempStoreFile first and the store after it
// (C++ destroys locals in reverse declaration order).
//
// MakePath is the plain static the callers use; the RAII guard
// wraps the same unique-path scheme for tests that keep the file across
// several scopes (create, destroy, raw-HighFive tamper, reopen).

#include <cstddef>
#include <filesystem>
#include <string>
#include <string_view>
#include <system_error>

namespace qcx::testing {

/// One unique temp path per call (the stem + a per-process counter). The
/// per-process counter restarts on every test-binary launch, so a path
/// generated by an earlier run (whose process is dead) can collide: any
/// file already at the path is removed first. Leaked files from crashed
/// runs are thereby harmless instead of being misread as an existing
/// store by the Create/Open exists() branch.
inline std::filesystem::path MakeTempStorePath(std::string_view stem) {
    static std::size_t counter = 0;
    const std::size_t id = counter++;
    const std::filesystem::path path = std::filesystem::temp_directory_path() /
                                       (std::string(stem) + "." + std::to_string(id) + ".h5");
    std::error_code ignored;
    std::filesystem::remove(path, ignored);
    return path;
}

/// The plain-path entry point.
class TempStoreFile {
public:
    /// A unique temp file path (no file is created - Create/Open own the
    /// file's lifetime).
    static std::filesystem::path MakePath(std::string_view stem) {
        return MakeTempStorePath(stem);
    }
};

/// RAII temp file: removes the file on destruction (best-effort - a stale
/// temp file is harmless: the path is unique per process and
/// MakeTempStorePath removes anything already at it, so EriStore::Create
/// never meets an existing file to refuse).
class ScopedTempStoreFile {
public:
    explicit ScopedTempStoreFile(std::string_view stem) : _path(MakeTempStorePath(stem)) {}

    ~ScopedTempStoreFile() {
        std::error_code ignored;
        std::filesystem::remove(_path, ignored);
    }

    ScopedTempStoreFile(const ScopedTempStoreFile&) = delete;
    ScopedTempStoreFile& operator=(const ScopedTempStoreFile&) = delete;

    const std::filesystem::path& Path() const noexcept {
        return _path;
    }

private:
    std::filesystem::path _path;
};

} // namespace qcx::testing
